[package]
name = "ambeelight"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
yeelight = "0.4.0-rc.1"
rgb2hex = { git = "https://github.com/callmenoodles/rgb2hex" }
tokio = { version = "1.15.0", features = ["full"]}
captrs = "0.3.1"
shuteye = "0.3.3"